query_template_list = [
    {"label": "Default (2 Joins and 1 Nested SELECT with 2 Joins)", "value": "SELECT s_name, r_name, ps_supplycost * ps_availqty AS total_cost FROM supplier, nation, region, ( SELECT ps_partkey, ps_suppkey, ps_availqty, ps_supplycost FROM partsupp, part, lineitem WHERE ps_partkey = p_partkey AND ps_partkey = l_partkey AND l_shipdate = '1997-01-01' ) AS ps WHERE s_suppkey = ps_suppkey AND s_nationkey = n_nationkey AND n_regionkey = r_regionkey AND r_name = 'ASIA' ORDER BY total_cost DESC;"},
    {"label": "Query 1 (4 Joins)", "value": "select supp_nation, cust_nation, l_year, sum(volume) as revenue from ( select n1.n_name as supp_nation, n2.n_name as cust_nation, extract(year from l_shipdate) as l_year, l_extendedprice * (1 - l_discount) as volume from supplier, lineitem, orders, customer, nation n1, nation n2 where s_suppkey = l_suppkey and o_orderkey = l_orderkey and c_custkey = o_custkey and s_nationkey = n1.n_nationkey and c_nationkey = n2.n_nationkey and ( (n1.n_name = 'UNITED STATES' and n2.n_name = 'EGYPT') or (n1.n_name = 'EGYPT' and n2.n_name = 'UNITED STATES') ) and l_shipdate between date '1995-01-01' and date '1996-12-31' ) as shipping group by supp_nation, cust_nation, l_year order by supp_nation, cust_nation, l_year"},
    {"label": "Query 2 (2 Joins)", "value": "select l_orderkey, sum(l_extendedprice * (1 - l_discount)) as revenue, o_orderdate, o_shippriority from customer, orders, lineitem where c_mktsegment = 'AUTOMOBILE' and c_custkey = o_custkey and l_orderkey = o_orderkey and o_orderdate = date '1995-03-25' and l_shipdate > date '1995-03-25' group by l_orderkey, o_orderdate, o_shippriority order by revenue desc, o_orderdate"},
    {"label": "Query 3 (2 Joins and 1 Nested SELECT with 2 Joins) ", "value": "SELECT c_name, o_orderdate, l_extendedprice FROM customer, orders, nation, ( SELECT l_orderkey, l_extendedprice, l_discount FROM lineitem, partsupp, supplier WHERE l_shipdate BETWEEN '1996-12-30' AND '1996-12-31' AND l_partkey = ps_partkey AND l_suppkey = ps_suppkey AND ps_suppkey = s_suppkey ) AS l WHERE c_custkey = o_custkey AND o_orderkey = l_orderkey AND c_nationkey = n_nationkey AND n_name = 'FRANCE'"},
    {"label": "Query 4 (1 Join and 1 Nested SELECT with 2 Joins)", "value": "SELECT c_name, o_orderdate, l_extendedprice * (1 - l_discount) AS discounted_price FROM customer, orders, ( SELECT l_orderkey, l_extendedprice, l_discount, s_name FROM lineitem, supplier, nation WHERE l_suppkey = s_suppkey AND s_nationkey = n_nationkey AND n_name = 'GERMANY' AND l_shipdate = '1997-01-01' ) AS l WHERE c_custkey = o_custkey AND o_orderkey = l_orderkey ORDER BY o_orderdate DESC;"},
    {"label": "Query 5 (1 Join and 1 Nested SELECT with 3 Joins)", "value": "SELECT c_name, o_orderdate, l_shipmode FROM customer, orders, ( SELECT l_orderkey, l_extendedprice, l_discount, l_shipmode FROM lineitem, supplier, nation, partsupp WHERE l_suppkey = s_suppkey AND s_nationkey = n_nationkey AND l_partkey = ps_partkey AND ps_suppkey = s_suppkey AND n_name = 'JAPAN' AND l_shipmode = 'AIR' ) AS l WHERE c_custkey = o_custkey AND o_orderkey = l_orderkey AND o_orderdate BETWEEN '1996-12-30' AND '1996-12-31'"}
]

